CREATE TABLE "USER" (
    "ID" SERIAL PRIMARY KEY,
    "USERNAME" VARCHAR(50) NOT NULL,
    "HASHED_PASSWORD" VARCHAR(1024),
    "HASH_SALT" VARCHAR(1024),
    "IS_ACTIVE" BOOLEAN,
    "FIRST_NAME" VARCHAR(50),
    "LAST_NAME" VARCHAR(50),
    "PROFILE_PIC_URL" VARCHAR(1024),
    "CREATED_AT" TIMESTAMP WITH TIME ZONE,
    "UPDATED_AT" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE "ROLE" (
    "ID" SERIAL PRIMARY KEY,
    "NAME" VARCHAR(1024) NOT NULL
);

CREATE TABLE "USER_ROLE" (
    "USER_ID" INTEGER REFERENCES "USER"("ID") ON DELETE CASCADE,
    "ROLE_ID" INTEGER REFERENCES "ROLE"("ID") ON DELETE CASCADE,
    PRIMARY KEY ("USER_ID", "ROLE_ID")
);

CREATE TABLE "EVENT_TYPE" (
    "ID" SERIAL PRIMARY KEY,
    "NAME" VARCHAR(1024) NOT NULL,
    "DESCRIPTION" VARCHAR(1024)
);

CREATE TABLE "ROLE_EVENT_TYPE" (
    "ROLE_ID" INTEGER REFERENCES "ROLE"("ID") ON DELETE CASCADE,
    "EVENT_TYPE_ID" INTEGER REFERENCES "EVENT_TYPE"("ID") ON DELETE CASCADE,
    "CAN_EDIT" BOOLEAN DEFAULT FALSE,
    "CAN_SEE" BOOLEAN DEFAULT FALSE,
    "CAN_ADD" BOOLEAN DEFAULT FALSE,
    PRIMARY KEY ("ROLE_ID", "EVENT_TYPE_ID")
);

CREATE TABLE "EVENT" (
    "ID" SERIAL PRIMARY KEY,
    "CREATED_BY" INTEGER REFERENCES "USER"("ID") ON DELETE CASCADE,
    "EVENT_TYPE" INTEGER REFERENCES "EVENT_TYPE"("ID") ON DELETE CASCADE,
    "TITLE" VARCHAR(1024) NOT NULL,
    "DESCRIPTION" VARCHAR(1024),
    "START_DATE" TIMESTAMP WITH TIME ZONE NOT NULL,
    "END_DATE" TIMESTAMP WITH TIME ZONE NOT NULL,
    "CREATED_AT" TIMESTAMP WITH TIME ZONE,
    "UPDATED_AT" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE "CONSTANTS" (
    "ID" SERIAL PRIMARY KEY,
    "NAME" VARCHAR(50) UNIQUE NOT NULL,
    "VALUE" VARCHAR(1024) NOT NULL
);

ALTER TABLE "EVENT"
ALTER COLUMN "START_DATE" TYPE TIMESTAMP WITH TIME ZONE 
USING "START_DATE"::timestamp with time zone;

ALTER TABLE "EVENT"
ALTER COLUMN "END_DATE" TYPE TIMESTAMP WITH TIME ZONE 
USING "END_DATE"::timestamp with time zone;
