name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.4'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up .env
      run: |
        echo "${{ secrets.ENCODED_ENV_VARIABLES }}" | base64 -d > env.json
        python -m json.tool env.json > env.json.tmp && mv env.json.tmp env.json
        python -c "import json; import os; with open('env.json') as f: data = json.load(f); for k, v in data.items(): os.system(f'echo {k}={v} >> .env')"
        rm env.json



    - name: Run Tests
      run: |
        pytest