name: Build and Test and Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.4'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up .env
        run: |
          echo "${{ secrets.ENV_VARIABLES }}" > .env

      - name: Run Tests
        run: |
          pytest

  deploy:
      runs-on: ubuntu-latest
      needs: build-and-test

      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Deploy to EC2
          env:
            PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
            HOST_NAME: ${{ secrets.HOST_DNS }}
            USER_NAME: ${{ secrets.USERNAME }}
            TARGET: ${{ secrets.TARGET_DIR }}

          run: |
            echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
            ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} "
            
              #Now we have got the access of EC2 and we will start the deploy .
              cd ${TARGET} &&
              git checkout master &&
              git fetch --all &&
              git reset --hard origin/master &&
              git pull origin master &&
              docker-compose up -d --build
            "
