name: Push-to-EC2

# Only trigger, when the Build and Test workflow succeeded
on:
  workflow_run:
    workflows: ["Build and Test"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to EC2 on successful build and test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: actions/checkout@v2

        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST_NAME: ${{ secrets.HOST_DNS }}
          USER_NAME: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
            #Now we have got the access of EC2 and we will start the deploy .
            cd ${TARGET} &&
            git checkout master &&
            git fetch --all &&
            git reset --hard origin/master &&
            git pull origin master &&
            docker-compose up -d --build